# Generated by Django 4.2.30 on 2026-09-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('CARETAKER', 'Caretaker'), ('TENANT', 'Tenant'), ('GUEST', 'Guest')], default='GUEST', max_length=20),
        ),
    ]
