# Generated by Django 4.2.10 on 2026-02-15 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('CHECKIN', 'Check-in'), ('CHECKOUT', 'Check-out')], max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('inspector_name', models.CharField(max_length=100)),
                ('condition_score', models.IntegerField(default=100)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='leases.lease')),
            ],
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='damage_photos/')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resolved', models.BooleanField(default=False)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='inspections.inspection')),
            ],
        ),
    ]
