# Generated by Django 4.2.30 on 2026-07-07 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='damage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='inspection',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='inspector_name',
        ),
        migrations.AddField(
            model_name='damage',
            name='charge_target',
            field=models.CharField(choices=[('TENANT_DEPOSIT', 'Deduct from Security Deposit'), ('LANDLORD_ACC', 'Landlord Expense (Wear & Tear)'), ('DIRECT_BILL', 'Invoice Tenant Directly')], default='TENANT_DEPOSIT', max_length=20),
        ),
        migrations.AddField(
            model_name='damage',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('PASSED', 'Passed Cleanly'), ('ISSUES_FOUND', 'Actionable Issues Found'), ('RECONCILED', 'Financials Settled / Closed')], default='PASSED', max_length=15),
        ),
        migrations.AlterField(
            model_name='damage',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_type',
            field=models.CharField(choices=[('CHECKIN', 'Check-in Baseline'), ('CHECKOUT', 'Check-out Assessment'), ('ROUTINE', 'Routine Maintenance Check')], default='ROUTINE', max_length=15),
        ),
    ]
