# Generated by Django 4.2 on 2026-06-02 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=50)),
                ('floor', models.IntegerField()),
                ('bedrooms', models.IntegerField(default=1)),
                ('window_panes', models.IntegerField(default=0)),
                ('bulbs', models.IntegerField(default=0)),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('VACANT', 'Vacant'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Maintenance'), ('RESERVED', 'Reserved')], default='VACANT', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property')),
            ],
        ),
    ]
