# Generated by Django 4.2 on 2026-06-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='damage_photo',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance_photos/'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='vendor_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='vendor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed by Vendor'), ('VERIFIED', 'Verified & Closed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
