# Generated by Django 4.2.30 on 2026-07-29 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenancerequest_damage_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'ordering': ['-created_at']},
        ),
    ]
