# Generated by Django 4.2.30 on 2026-07-07 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leases', '0002_alter_lease_status'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_refunded', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deductions_retained', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount withheld to settle damage invoices or unpaid utility/rent balances.', max_digits=12)),
                ('payment_method', models.CharField(choices=[('MPESA', 'M-Pesa Mobile Money'), ('CARD', 'Credit/Debit Card'), ('BANK_TRANSFER', 'Direct Bank Deposit'), ('CASH', 'Physical Cash Receipt')], default='BANK_TRANSFER', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Reasoning for partial deductions or refund metadata.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_refunds', to='leases.lease')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
