# Generated by Django 4.2.30 on 2026-07-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('ACTIVE', 'Active'), ('TERMINATED', 'Terminated')], default='PENDING', max_length=20),
        ),
    ]
